import { sortByDate } from '../utils'
import matter from 'gray-matter';
import fetchRepoTree from '../lib/fetchRepoTree'
import fetchMarkdown from '../lib/fetchMarkdown'
import Head from 'next/head'
import Post from '../components/Post'

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Abe Hidek Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="posts">
        {posts.map((post, index) => (
          <Post key={ index } post = { post } />
        ))}
      </div>
    </div>
  )
}

async function getPosts(folders) {
  const files = folders;
  const posts = [];

  for (const slug of files) {
    const md = await fetchMarkdown(slug)
    const { data: frontmatter } = matter(md)
    if (!frontmatter.cover_image.startsWith("http")){
      if (frontmatter.cover_image.startsWith("/")) {
        frontmatter.cover_image = frontmatter.cover_image.replace(/^/, `${process.env.cdnRaw}/${slug}` )
      }
      else {
        frontmatter.cover_image = frontmatter.cover_image.replace(/^/, `${process.env.cdnRaw}/${slug}/` )
      }
    }
    posts.push({
      slug: slug,
      frontmatter: frontmatter
    })
  }
  return posts
}

export async function getStaticProps() {
  const folders = await fetchRepoTree()
  // Get slug and frontmatter
  const posts = await getPosts(folders)
  return {
    props: {
      posts: posts.sort(sortByDate),
    },
    revalidate: 60,
  }
}
