import Head from 'next/head'
import matter from 'gray-matter';
import Post from '../components/Post'
import { sortByDate } from '../utils'

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Abe Hidek Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="posts">
        {posts.map((post, index) => (
          <Post key={ index } post = { post } />
        ))}
      </div>
    </div>
  )
}

async function getPosts(folders) {
  const files = folders;
  const posts = [];

  for (const slug of files) {
    const mdPromise = await fetch(`https://www.gitlab.com/abehidek/posts/-/raw/main/${slug}/main.md`)
    const md = await mdPromise.text()
    const { data: frontmatter } = matter(md)
    if (!frontmatter.cover_image.startsWith("http")){
      frontmatter.cover_image = frontmatter.cover_image.replace(/^/, `https://www.gitlab.com/abehidek/posts/-/raw/main/${slug}/` )
    }
    posts.push({
      slug: slug,
      frontmatter: frontmatter
    })
  }
  return posts
}

export async function getServerSideProps() {
  const contents = await fetch("https://gitlab.com/abehidek/posts/-/refs/main/logs_tree/?format=json&offset=0")
  const response = await contents.json()
  const folders = []

  response.map(content => {
    if (content.type == "tree"){
      folders.push(content.file_name)
    }
  })
  // Get slug and frontmatter
  const posts = await getPosts(folders)
  return {
    props: {
      posts: posts.sort(sortByDate),
    }
  }
}
