import type { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";
import Head from "next/head";
import getRSS from "../lib/rss";

const Home: NextPage = () => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-2 lg:w-2/3"></div>
        {data ? (
          <button
            className="bg-blue-500 px-5 py-3 text-white "
            onClick={() => signOut()}
          >
            Sign Out {data.user?.name}
          </button>
        ) : (
          <button
            className="bg-blue-500 px-5 py-3 text-white "
            onClick={() => signIn("github")}
          >
            Sign In
          </button>
        )}
      </main>
    </>
  );
};

export async function getStaticProps() {
  await getRSS();
  return { props: {} };
}

export default Home;
