import SnippetsComponent from "@/src/components/Snippets";
import { getAllSnippets, SnippetMeta } from "@/src/server/services/snippets";
import type { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";
import Head from "next/head";

const SnippetsPage: NextPage<{ allSnippetsMeta: SnippetMeta[] }> = ({
  allSnippetsMeta,
}) => {
  const { data } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <p>Snippets</p>
        <SnippetsComponent allSnippetsMeta={allSnippetsMeta} />
      </main>
    </>
  );
};

export async function getStaticProps() {
  const allSnippets = await getAllSnippets();
  const allSnippetsMeta = await Promise.all(
    allSnippets.map((snippet) => snippet.meta)
  );

  return { props: { allSnippetsMeta }, revalidate: 30 };
}

export default SnippetsPage;
