import type { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useForm } from "react-hook-form";

const Home: NextPage = () => {
  const {
    data: secretMessageData,
    refetch: refetchSecretMessage,
    isError: isErrorSecretMessage,
    error: errorSecretMessage,
  } = trpc.useQuery(["auth.getSecretMessage"], {
    enabled: false,
    retry: false,
  });

  const { data: allExample, refetch: refetchGetAll } = trpc.useQuery(
    ["example.getAll"],
    {}
  );

  const { data: session } = useSession();

  const { mutate: changePassword } = trpc.useMutation(["user.changePassword"], {
    onSuccess: () => alert("Sent request to change pwd"),
  });

  type ChangePassword = {
    password: string;
  };

  const {
    register: registerChangePasswordField,
    handleSubmit: handleChangePasswordSubmit,
  } = useForm<ChangePassword>();

  const onSubmitChangePassword = handleChangePasswordSubmit((data) =>
    changePassword(data)
  );

  const { mutate: addOne } = trpc.useMutation(["example.addOne"], {
    onSuccess: () => alert("Succefully created new one"),
  });

  type AddOne = {
    name: string;
    description: string;
  };

  const { register: registerAddOneField, handleSubmit: handleAddOneSubmit } =
    useForm<AddOne>();

  const onSubmitAddOne = handleAddOneSubmit((data) => addOne(data));

  return (
    <>
      <Head>
        <title>CT3A - NextAuth Db Session Credentials Provider POC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col justify-center min-h-screen p-4">
        <h1 className="text-3xl font-bold">
          Create T3 App - NextAuth Database Session with Credentials Provider
          Proof of Concept
        </h1>
        <div className="mt-5 border-2 p-5 flex flex-col justify-center">
          <div className="flex items-center w-full">
            {secretMessageData ? (
              <p>{secretMessageData}</p>
            ) : isErrorSecretMessage ? (
              <p>{errorSecretMessage.message}</p>
            ) : (
              <p>Click below to test your authorization</p>
            )}
          </div>
          <div>
            <button
              onClick={() => refetchSecretMessage()}
              className="bg-blue-500 text-white px-5 py-3"
            >
              fetch from trpc
            </button>
          </div>
        </div>

        <div className="mt-5 border-2 p-5 flex flex-col justify-center">
          <h1>Authenticate and sign out here!</h1>
          {session ? (
            <>
              <button
                onClick={() => signOut()}
                className="bg-blue-500 text-white px-3 py-3 mt-2"
              >
                Sign Out - {session.user?.name}
              </button>
            </>
          ) : (
            <div className="flex w-full gap-2">
              <button
                onClick={() => signIn("github")}
                className="bg-blue-500 text-white px-3 py-3 mt-2"
              >
                Sign In With Github
              </button>
              <button
                onClick={() => signIn()}
                className="bg-blue-500 text-white px-3 py-3 mt-2"
              >
                Sign In With Email
              </button>
            </div>
          )}
        </div>
        <div className="mt-5 border-2 p-5 flex flex-col justify-center">
          <h1>
            You can add password if you signed in with your Github, or just
            change the pwd
          </h1>
          <form onSubmit={onSubmitChangePassword}>
            <input
              type="password"
              className="border-2 px-5 py-3"
              placeholder="min: 8 char long"
              {...registerChangePasswordField("password")}
            />
            <input
              className="bg-green-500 text-white px-3 py-3 mt-2"
              type="submit"
              value="Change password"
            />
          </form>
        </div>

        <div className="mt-5 border-2 p-5 flex flex-col justify-center">
          <h1>This is just a db test</h1>
          <pre>{JSON.stringify(allExample, null, 2)}</pre>

          <form className="flex gap-2" onSubmit={onSubmitAddOne}>
            <input
              type="text"
              {...registerAddOneField("name")}
              className="border-2 px-5 py-3"
              placeholder="name..."
            />
            <input
              type="text"
              {...registerAddOneField("description")}
              className="border-2 px-5 py-3"
              placeholder="description..."
            />
            <input
              className="bg-green-500 text-white px-3 py-3"
              type="submit"
              value="Add todo"
            />
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;
