[package]
name = "learning-rust"
version = "0.1.0"
authors = ["abehidek"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
rand = "0.8.5"